// <auto-generated />
using GanemoScreen.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GanemoScreen.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GanemoScreen.Model.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Guides");
                });

            modelBuilder.Entity("GanemoScreen.Model.ImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Image");

                    b.Property<string>("ImageInfo");

                    b.HasKey("Id");

                    b.ToTable("imageEntities");
                });

            modelBuilder.Entity("GanemoScreen.Model.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("Duration");

                    b.Property<int?>("GuideId");

                    b.Property<string>("Note");

                    b.Property<string>("Time");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("GanemoScreen.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GanemoScreen.Model.Lesson", b =>
                {
                    b.HasOne("GanemoScreen.Model.Guide", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId");
                });
#pragma warning restore 612, 618
        }
    }
}
